// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: kafka_messages.proto

package kafka_messages_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message sent from TaskManager to TaskWorker to request task execution
type KafkaTaskDispatch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId         uint32 `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TaskTemplateId uint32 `protobuf:"varint,2,opt,name=task_template_id,json=taskTemplateId,proto3" json:"task_template_id,omitempty"`
	Name           string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Params         string `protobuf:"bytes,4,opt,name=params,proto3" json:"params,omitempty"`                                 // JSON string for task parameters
	ExecutorType   string `protobuf:"bytes,5,opt,name=executor_type,json=executorType,proto3" json:"executor_type,omitempty"` // Specifies which worker/plugin handles this task type
	ParamSchema    string `protobuf:"bytes,6,opt,name=param_schema,json=paramSchema,proto3" json:"param_schema,omitempty"`    // Optional: JSON schema for params, for worker-side validation
}

func (x *KafkaTaskDispatch) Reset() {
	*x = KafkaTaskDispatch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kafka_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KafkaTaskDispatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KafkaTaskDispatch) ProtoMessage() {}

func (x *KafkaTaskDispatch) ProtoReflect() protoreflect.Message {
	mi := &file_kafka_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KafkaTaskDispatch.ProtoReflect.Descriptor instead.
func (*KafkaTaskDispatch) Descriptor() ([]byte, []int) {
	return file_kafka_messages_proto_rawDescGZIP(), []int{0}
}

func (x *KafkaTaskDispatch) GetTaskId() uint32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *KafkaTaskDispatch) GetTaskTemplateId() uint32 {
	if x != nil {
		return x.TaskTemplateId
	}
	return 0
}

func (x *KafkaTaskDispatch) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *KafkaTaskDispatch) GetParams() string {
	if x != nil {
		return x.Params
	}
	return ""
}

func (x *KafkaTaskDispatch) GetExecutorType() string {
	if x != nil {
		return x.ExecutorType
	}
	return ""
}

func (x *KafkaTaskDispatch) GetParamSchema() string {
	if x != nil {
		return x.ParamSchema
	}
	return ""
}

// Message sent from TaskWorker to TaskManager with the result of a task execution
type KafkaTaskCompletion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId       uint32 `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status       string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                                 // e.g., COMPLETED, FAILED
	Result       string `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`                                 // JSON string for task result (if status is COMPLETED)
	ErrorMessage string `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // Error details (if status is FAILED)
}

func (x *KafkaTaskCompletion) Reset() {
	*x = KafkaTaskCompletion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kafka_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KafkaTaskCompletion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KafkaTaskCompletion) ProtoMessage() {}

func (x *KafkaTaskCompletion) ProtoReflect() protoreflect.Message {
	mi := &file_kafka_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KafkaTaskCompletion.ProtoReflect.Descriptor instead.
func (*KafkaTaskCompletion) Descriptor() ([]byte, []int) {
	return file_kafka_messages_proto_rawDescGZIP(), []int{1}
}

func (x *KafkaTaskCompletion) GetTaskId() uint32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *KafkaTaskCompletion) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *KafkaTaskCompletion) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *KafkaTaskCompletion) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_kafka_messages_proto protoreflect.FileDescriptor

var file_kafka_messages_proto_rawDesc = []byte{
	0x0a, 0x14, 0x6b, 0x61, 0x66, 0x6b, 0x61, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6b, 0x61,
	0x66, 0x6b, 0x61, 0x22, 0xca, 0x01, 0x0a, 0x11, 0x4b, 0x61, 0x66, 0x6b, 0x61, 0x54, 0x61, 0x73,
	0x6b, 0x44, 0x69, 0x73, 0x70, 0x61, 0x74, 0x63, 0x68, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x61, 0x73,
	0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b,
	0x49, 0x64, 0x12, 0x28, 0x0a, 0x10, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x74, 0x65, 0x6d, 0x70, 0x6c,
	0x61, 0x74, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0e, 0x74, 0x61,
	0x73, 0x6b, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x65, 0x78, 0x65, 0x63,
	0x75, 0x74, 0x6f, 0x72, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x21, 0x0a,
	0x0c, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x5f, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61,
	0x22, 0x83, 0x01, 0x0a, 0x13, 0x4b, 0x61, 0x66, 0x6b, 0x61, 0x54, 0x61, 0x73, 0x6b, 0x43, 0x6f,
	0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x61, 0x73, 0x6b,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x12, 0x23, 0x0a, 0x0d, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x44, 0x5a, 0x42, 0x74, 0x61, 0x73, 0x6b, 0x2d, 0x6d,
	0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x2f, 0x6b, 0x61, 0x66, 0x6b, 0x61, 0x5f, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x5f, 0x70, 0x62, 0x3b, 0x6b, 0x61, 0x66, 0x6b, 0x61,
	0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x5f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_kafka_messages_proto_rawDescOnce sync.Once
	file_kafka_messages_proto_rawDescData = file_kafka_messages_proto_rawDesc
)

func file_kafka_messages_proto_rawDescGZIP() []byte {
	file_kafka_messages_proto_rawDescOnce.Do(func() {
		file_kafka_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_kafka_messages_proto_rawDescData)
	})
	return file_kafka_messages_proto_rawDescData
}

var file_kafka_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_kafka_messages_proto_goTypes = []interface{}{
	(*KafkaTaskDispatch)(nil),   // 0: proto.kafka.KafkaTaskDispatch
	(*KafkaTaskCompletion)(nil), // 1: proto.kafka.KafkaTaskCompletion
}
var file_kafka_messages_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kafka_messages_proto_init() }
func file_kafka_messages_proto_init() {
	if File_kafka_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_kafka_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KafkaTaskDispatch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kafka_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KafkaTaskCompletion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kafka_messages_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kafka_messages_proto_goTypes,
		DependencyIndexes: file_kafka_messages_proto_depIdxs,
		MessageInfos:      file_kafka_messages_proto_msgTypes,
	}.Build()
	File_kafka_messages_proto = out.File
	file_kafka_messages_proto_rawDesc = nil
	file_kafka_messages_proto_goTypes = nil
	file_kafka_messages_proto_depIdxs = nil
}
