// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: task_template_service.proto

package task_template_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TaskTemplate message mirrors the GORM model structure
type TaskTemplate struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // Using uint32 as GORM default ID is uint
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	TaskType       string                 `protobuf:"bytes,4,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
	ParamSchema    string                 `protobuf:"bytes,5,opt,name=param_schema,json=paramSchema,proto3" json:"param_schema,omitempty"`    // JSON schema string
	ResultSchema   string                 `protobuf:"bytes,6,opt,name=result_schema,json=resultSchema,proto3" json:"result_schema,omitempty"` // JSON schema string
	ExecutorType   string                 `protobuf:"bytes,7,opt,name=executor_type,json=executorType,proto3" json:"executor_type,omitempty"`
	CronExpression string                 `protobuf:"bytes,8,opt,name=cron_expression,json=cronExpression,proto3" json:"cron_expression,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TaskTemplate) Reset() {
	*x = TaskTemplate{}
	mi := &file_task_template_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskTemplate) ProtoMessage() {}

func (x *TaskTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_task_template_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskTemplate.ProtoReflect.Descriptor instead.
func (*TaskTemplate) Descriptor() ([]byte, []int) {
	return file_task_template_service_proto_rawDescGZIP(), []int{0}
}

func (x *TaskTemplate) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TaskTemplate) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TaskTemplate) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TaskTemplate) GetTaskType() string {
	if x != nil {
		return x.TaskType
	}
	return ""
}

func (x *TaskTemplate) GetParamSchema() string {
	if x != nil {
		return x.ParamSchema
	}
	return ""
}

func (x *TaskTemplate) GetResultSchema() string {
	if x != nil {
		return x.ResultSchema
	}
	return ""
}

func (x *TaskTemplate) GetExecutorType() string {
	if x != nil {
		return x.ExecutorType
	}
	return ""
}

func (x *TaskTemplate) GetCronExpression() string {
	if x != nil {
		return x.CronExpression
	}
	return ""
}

func (x *TaskTemplate) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *TaskTemplate) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateTaskTemplateRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	TaskType       string                 `protobuf:"bytes,3,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
	ParamSchema    string                 `protobuf:"bytes,4,opt,name=param_schema,json=paramSchema,proto3" json:"param_schema,omitempty"`
	ResultSchema   string                 `protobuf:"bytes,5,opt,name=result_schema,json=resultSchema,proto3" json:"result_schema,omitempty"`
	ExecutorType   string                 `protobuf:"bytes,6,opt,name=executor_type,json=executorType,proto3" json:"executor_type,omitempty"`
	CronExpression string                 `protobuf:"bytes,7,opt,name=cron_expression,json=cronExpression,proto3" json:"cron_expression,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateTaskTemplateRequest) Reset() {
	*x = CreateTaskTemplateRequest{}
	mi := &file_task_template_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskTemplateRequest) ProtoMessage() {}

func (x *CreateTaskTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_template_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskTemplateRequest.ProtoReflect.Descriptor instead.
func (*CreateTaskTemplateRequest) Descriptor() ([]byte, []int) {
	return file_task_template_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTaskTemplateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTaskTemplateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateTaskTemplateRequest) GetTaskType() string {
	if x != nil {
		return x.TaskType
	}
	return ""
}

func (x *CreateTaskTemplateRequest) GetParamSchema() string {
	if x != nil {
		return x.ParamSchema
	}
	return ""
}

func (x *CreateTaskTemplateRequest) GetResultSchema() string {
	if x != nil {
		return x.ResultSchema
	}
	return ""
}

func (x *CreateTaskTemplateRequest) GetExecutorType() string {
	if x != nil {
		return x.ExecutorType
	}
	return ""
}

func (x *CreateTaskTemplateRequest) GetCronExpression() string {
	if x != nil {
		return x.CronExpression
	}
	return ""
}

type CreateTaskTemplateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Template      *TaskTemplate          `protobuf:"bytes,1,opt,name=template,proto3" json:"template,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskTemplateResponse) Reset() {
	*x = CreateTaskTemplateResponse{}
	mi := &file_task_template_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskTemplateResponse) ProtoMessage() {}

func (x *CreateTaskTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_template_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskTemplateResponse.ProtoReflect.Descriptor instead.
func (*CreateTaskTemplateResponse) Descriptor() ([]byte, []int) {
	return file_task_template_service_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTaskTemplateResponse) GetTemplate() *TaskTemplate {
	if x != nil {
		return x.Template
	}
	return nil
}

type GetTaskTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskTemplateRequest) Reset() {
	*x = GetTaskTemplateRequest{}
	mi := &file_task_template_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskTemplateRequest) ProtoMessage() {}

func (x *GetTaskTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_template_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskTemplateRequest.ProtoReflect.Descriptor instead.
func (*GetTaskTemplateRequest) Descriptor() ([]byte, []int) {
	return file_task_template_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetTaskTemplateRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetTaskTemplateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Template      *TaskTemplate          `protobuf:"bytes,1,opt,name=template,proto3" json:"template,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskTemplateResponse) Reset() {
	*x = GetTaskTemplateResponse{}
	mi := &file_task_template_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskTemplateResponse) ProtoMessage() {}

func (x *GetTaskTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_template_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskTemplateResponse.ProtoReflect.Descriptor instead.
func (*GetTaskTemplateResponse) Descriptor() ([]byte, []int) {
	return file_task_template_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetTaskTemplateResponse) GetTemplate() *TaskTemplate {
	if x != nil {
		return x.Template
	}
	return nil
}

type ListTaskTemplatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTaskTemplatesRequest) Reset() {
	*x = ListTaskTemplatesRequest{}
	mi := &file_task_template_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTaskTemplatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTaskTemplatesRequest) ProtoMessage() {}

func (x *ListTaskTemplatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_template_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTaskTemplatesRequest.ProtoReflect.Descriptor instead.
func (*ListTaskTemplatesRequest) Descriptor() ([]byte, []int) {
	return file_task_template_service_proto_rawDescGZIP(), []int{5}
}

type ListTaskTemplatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Templates     []*TaskTemplate        `protobuf:"bytes,1,rep,name=templates,proto3" json:"templates,omitempty"` // string next_page_token = 2;
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTaskTemplatesResponse) Reset() {
	*x = ListTaskTemplatesResponse{}
	mi := &file_task_template_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTaskTemplatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTaskTemplatesResponse) ProtoMessage() {}

func (x *ListTaskTemplatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_template_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTaskTemplatesResponse.ProtoReflect.Descriptor instead.
func (*ListTaskTemplatesResponse) Descriptor() ([]byte, []int) {
	return file_task_template_service_proto_rawDescGZIP(), []int{6}
}

func (x *ListTaskTemplatesResponse) GetTemplates() []*TaskTemplate {
	if x != nil {
		return x.Templates
	}
	return nil
}

type UpdateTaskTemplateRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	TaskType       string                 `protobuf:"bytes,4,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
	ParamSchema    string                 `protobuf:"bytes,5,opt,name=param_schema,json=paramSchema,proto3" json:"param_schema,omitempty"`
	ResultSchema   string                 `protobuf:"bytes,6,opt,name=result_schema,json=resultSchema,proto3" json:"result_schema,omitempty"`
	ExecutorType   string                 `protobuf:"bytes,7,opt,name=executor_type,json=executorType,proto3" json:"executor_type,omitempty"`
	CronExpression string                 `protobuf:"bytes,8,opt,name=cron_expression,json=cronExpression,proto3" json:"cron_expression,omitempty"` // google.protobuf.FieldMask update_mask = 9; // For partial updates
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateTaskTemplateRequest) Reset() {
	*x = UpdateTaskTemplateRequest{}
	mi := &file_task_template_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTaskTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskTemplateRequest) ProtoMessage() {}

func (x *UpdateTaskTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_template_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskTemplateRequest.ProtoReflect.Descriptor instead.
func (*UpdateTaskTemplateRequest) Descriptor() ([]byte, []int) {
	return file_task_template_service_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateTaskTemplateRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateTaskTemplateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateTaskTemplateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateTaskTemplateRequest) GetTaskType() string {
	if x != nil {
		return x.TaskType
	}
	return ""
}

func (x *UpdateTaskTemplateRequest) GetParamSchema() string {
	if x != nil {
		return x.ParamSchema
	}
	return ""
}

func (x *UpdateTaskTemplateRequest) GetResultSchema() string {
	if x != nil {
		return x.ResultSchema
	}
	return ""
}

func (x *UpdateTaskTemplateRequest) GetExecutorType() string {
	if x != nil {
		return x.ExecutorType
	}
	return ""
}

func (x *UpdateTaskTemplateRequest) GetCronExpression() string {
	if x != nil {
		return x.CronExpression
	}
	return ""
}

type UpdateTaskTemplateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Template      *TaskTemplate          `protobuf:"bytes,1,opt,name=template,proto3" json:"template,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTaskTemplateResponse) Reset() {
	*x = UpdateTaskTemplateResponse{}
	mi := &file_task_template_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTaskTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskTemplateResponse) ProtoMessage() {}

func (x *UpdateTaskTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_template_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskTemplateResponse.ProtoReflect.Descriptor instead.
func (*UpdateTaskTemplateResponse) Descriptor() ([]byte, []int) {
	return file_task_template_service_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateTaskTemplateResponse) GetTemplate() *TaskTemplate {
	if x != nil {
		return x.Template
	}
	return nil
}

type DeleteTaskTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTaskTemplateRequest) Reset() {
	*x = DeleteTaskTemplateRequest{}
	mi := &file_task_template_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTaskTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTaskTemplateRequest) ProtoMessage() {}

func (x *DeleteTaskTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_template_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTaskTemplateRequest.ProtoReflect.Descriptor instead.
func (*DeleteTaskTemplateRequest) Descriptor() ([]byte, []int) {
	return file_task_template_service_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteTaskTemplateRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_task_template_service_proto protoreflect.FileDescriptor

const file_task_template_service_proto_rawDesc = "" +
	"\n" +
	"\x1btask_template_service.proto\x12\x13proto.task_template\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xfd\x02\n" +
	"\fTaskTemplate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\ttask_type\x18\x04 \x01(\tR\btaskType\x12!\n" +
	"\fparam_schema\x18\x05 \x01(\tR\vparamSchema\x12#\n" +
	"\rresult_schema\x18\x06 \x01(\tR\fresultSchema\x12#\n" +
	"\rexecutor_type\x18\a \x01(\tR\fexecutorType\x12'\n" +
	"\x0fcron_expression\x18\b \x01(\tR\x0ecronExpression\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x84\x02\n" +
	"\x19CreateTaskTemplateRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1b\n" +
	"\ttask_type\x18\x03 \x01(\tR\btaskType\x12!\n" +
	"\fparam_schema\x18\x04 \x01(\tR\vparamSchema\x12#\n" +
	"\rresult_schema\x18\x05 \x01(\tR\fresultSchema\x12#\n" +
	"\rexecutor_type\x18\x06 \x01(\tR\fexecutorType\x12'\n" +
	"\x0fcron_expression\x18\a \x01(\tR\x0ecronExpression\"[\n" +
	"\x1aCreateTaskTemplateResponse\x12=\n" +
	"\btemplate\x18\x01 \x01(\v2!.proto.task_template.TaskTemplateR\btemplate\"(\n" +
	"\x16GetTaskTemplateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"X\n" +
	"\x17GetTaskTemplateResponse\x12=\n" +
	"\btemplate\x18\x01 \x01(\v2!.proto.task_template.TaskTemplateR\btemplate\"\x1a\n" +
	"\x18ListTaskTemplatesRequest\"\\\n" +
	"\x19ListTaskTemplatesResponse\x12?\n" +
	"\ttemplates\x18\x01 \x03(\v2!.proto.task_template.TaskTemplateR\ttemplates\"\x94\x02\n" +
	"\x19UpdateTaskTemplateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\ttask_type\x18\x04 \x01(\tR\btaskType\x12!\n" +
	"\fparam_schema\x18\x05 \x01(\tR\vparamSchema\x12#\n" +
	"\rresult_schema\x18\x06 \x01(\tR\fresultSchema\x12#\n" +
	"\rexecutor_type\x18\a \x01(\tR\fexecutorType\x12'\n" +
	"\x0fcron_expression\x18\b \x01(\tR\x0ecronExpression\"[\n" +
	"\x1aUpdateTaskTemplateResponse\x12=\n" +
	"\btemplate\x18\x01 \x01(\v2!.proto.task_template.TaskTemplateR\btemplate\"+\n" +
	"\x19DeleteTaskTemplateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id2\xcd\x04\n" +
	"\x13TaskTemplateService\x12w\n" +
	"\x12CreateTaskTemplate\x12..proto.task_template.CreateTaskTemplateRequest\x1a/.proto.task_template.CreateTaskTemplateResponse\"\x00\x12n\n" +
	"\x0fGetTaskTemplate\x12+.proto.task_template.GetTaskTemplateRequest\x1a,.proto.task_template.GetTaskTemplateResponse\"\x00\x12t\n" +
	"\x11ListTaskTemplates\x12-.proto.task_template.ListTaskTemplatesRequest\x1a..proto.task_template.ListTaskTemplatesResponse\"\x00\x12w\n" +
	"\x12UpdateTaskTemplate\x12..proto.task_template.UpdateTaskTemplateRequest\x1a/.proto.task_template.UpdateTaskTemplateResponse\"\x00\x12^\n" +
	"\x12DeleteTaskTemplate\x12..proto.task_template.DeleteTaskTemplateRequest\x1a\x16.google.protobuf.Empty\"\x00BBZ@task-management-service/pkg/pb/task_template_pb;task_template_pbb\x06proto3"

var (
	file_task_template_service_proto_rawDescOnce sync.Once
	file_task_template_service_proto_rawDescData []byte
)

func file_task_template_service_proto_rawDescGZIP() []byte {
	file_task_template_service_proto_rawDescOnce.Do(func() {
		file_task_template_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_task_template_service_proto_rawDesc), len(file_task_template_service_proto_rawDesc)))
	})
	return file_task_template_service_proto_rawDescData
}

var file_task_template_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_task_template_service_proto_goTypes = []any{
	(*TaskTemplate)(nil),               // 0: proto.task_template.TaskTemplate
	(*CreateTaskTemplateRequest)(nil),  // 1: proto.task_template.CreateTaskTemplateRequest
	(*CreateTaskTemplateResponse)(nil), // 2: proto.task_template.CreateTaskTemplateResponse
	(*GetTaskTemplateRequest)(nil),     // 3: proto.task_template.GetTaskTemplateRequest
	(*GetTaskTemplateResponse)(nil),    // 4: proto.task_template.GetTaskTemplateResponse
	(*ListTaskTemplatesRequest)(nil),   // 5: proto.task_template.ListTaskTemplatesRequest
	(*ListTaskTemplatesResponse)(nil),  // 6: proto.task_template.ListTaskTemplatesResponse
	(*UpdateTaskTemplateRequest)(nil),  // 7: proto.task_template.UpdateTaskTemplateRequest
	(*UpdateTaskTemplateResponse)(nil), // 8: proto.task_template.UpdateTaskTemplateResponse
	(*DeleteTaskTemplateRequest)(nil),  // 9: proto.task_template.DeleteTaskTemplateRequest
	(*timestamppb.Timestamp)(nil),      // 10: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),              // 11: google.protobuf.Empty
}
var file_task_template_service_proto_depIdxs = []int32{
	10, // 0: proto.task_template.TaskTemplate.created_at:type_name -> google.protobuf.Timestamp
	10, // 1: proto.task_template.TaskTemplate.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: proto.task_template.CreateTaskTemplateResponse.template:type_name -> proto.task_template.TaskTemplate
	0,  // 3: proto.task_template.GetTaskTemplateResponse.template:type_name -> proto.task_template.TaskTemplate
	0,  // 4: proto.task_template.ListTaskTemplatesResponse.templates:type_name -> proto.task_template.TaskTemplate
	0,  // 5: proto.task_template.UpdateTaskTemplateResponse.template:type_name -> proto.task_template.TaskTemplate
	1,  // 6: proto.task_template.TaskTemplateService.CreateTaskTemplate:input_type -> proto.task_template.CreateTaskTemplateRequest
	3,  // 7: proto.task_template.TaskTemplateService.GetTaskTemplate:input_type -> proto.task_template.GetTaskTemplateRequest
	5,  // 8: proto.task_template.TaskTemplateService.ListTaskTemplates:input_type -> proto.task_template.ListTaskTemplatesRequest
	7,  // 9: proto.task_template.TaskTemplateService.UpdateTaskTemplate:input_type -> proto.task_template.UpdateTaskTemplateRequest
	9,  // 10: proto.task_template.TaskTemplateService.DeleteTaskTemplate:input_type -> proto.task_template.DeleteTaskTemplateRequest
	2,  // 11: proto.task_template.TaskTemplateService.CreateTaskTemplate:output_type -> proto.task_template.CreateTaskTemplateResponse
	4,  // 12: proto.task_template.TaskTemplateService.GetTaskTemplate:output_type -> proto.task_template.GetTaskTemplateResponse
	6,  // 13: proto.task_template.TaskTemplateService.ListTaskTemplates:output_type -> proto.task_template.ListTaskTemplatesResponse
	8,  // 14: proto.task_template.TaskTemplateService.UpdateTaskTemplate:output_type -> proto.task_template.UpdateTaskTemplateResponse
	11, // 15: proto.task_template.TaskTemplateService.DeleteTaskTemplate:output_type -> google.protobuf.Empty
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_task_template_service_proto_init() }
func file_task_template_service_proto_init() {
	if File_task_template_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_task_template_service_proto_rawDesc), len(file_task_template_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_task_template_service_proto_goTypes,
		DependencyIndexes: file_task_template_service_proto_depIdxs,
		MessageInfos:      file_task_template_service_proto_msgTypes,
	}.Build()
	File_task_template_service_proto = out.File
	file_task_template_service_proto_goTypes = nil
	file_task_template_service_proto_depIdxs = nil
}
